name: grad_tracker
description: A simple app to track graduation requirements
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # State Management
  provider: ^6.0.5
  
  # Data Storage
  shared_preferences: ^2.2.3
  
  # Navigation
  go_router: ^12.1.3
  
  # Charts
  fl_chart: ^0.65.0
  
  # Utilities
  intl: ^0.19.0

flutter:
  uses-material-design: true
  generate: true

