import 'package:flutter/foundation.dart';
import 'course.dart';
import 'course_group.dart';

//Khối kiến thức
class Section with ChangeNotifier {
  final String id;
  final String name;
  final String description;
  final int requiredCredits;
  final int optionalCredits;
  final List<CourseGroup> courseGroups;

  Section({
    required this.id,
    required this.name,
    required this.description,
    required this.requiredCredits,
    required this.optionalCredits,
    required this.courseGroups,
  });

  List<Course> get allCourses => courseGroups.expand((group) => group.courses).toList();

  int get totalCredits => requiredCredits + optionalCredits;

  int get completedCredits => allCourses.fold(
      0, (sum, course) => sum + (course.isCompleted ? course.credits : 0));

  int get remainingCredits => totalCredits - completedCredits;

  double get progress =>
      requiredCredits > 0 ? completedCredits / requiredCredits : 0;

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'name': name,
      'description': description,
      'requiredCredits': requiredCredits,
      'optionalCredits': optionalCredits,
      'courseGroups': courseGroups.map((group) => group.toJson()).toList(),
    };
  }

  factory Section.fromJson(Map<String, dynamic> json) {
    return Section(
      id: json['id'],
      name: json['name'],
      description: json['description'],
      requiredCredits: json['requiredCredits'],
      optionalCredits: json['optionalCredits'],
      courseGroups: (json['courseGroups'] as List)
          .map((groupJson) => CourseGroup.fromJson(groupJson))
          .toList(),
    );
  }

    static templateData() async {
    final sections = [
      Section(
        name: 'Kiến thức giáo dục đại cương',
        requiredCredits: 34,
        optionalCredits: 22,
        description: 'Các môn học cơ bản, rèn luyện tư duy và kỹ năng',
        id: '1',
        courseGroups: [
          CourseGroup(
            id: '1.1',
            name: 'Lý luận chính trị',
            description: 'Các môn học về lý luận chính trị',
            requiredCredits: 11,
            optionalCredits: 0,
            courses: [
              Course(
                name: 'Triết học Mác - Lênin',
                credits: 3,
                id: 'BAA00101',
                type: CourseType.required,
                status: CourseStatus.completed,
                score: 5.6,
                prerequisiteCourses: [],
              ),
              Course(
                name: 'Kinh tế chính trị Mác - Lênin',
                credits: 2,
                id: 'BAA00102',
                type: CourseType.required,
                status: CourseStatus.notStarted,
                prerequisiteCourses: [],
              ),
              Course(
                name: 'Chủ nghĩa xã hội khoa học',
                credits: 2,
                id: 'BAA00103',
                type: CourseType.required,
                status: CourseStatus.notStarted,
                prerequisiteCourses: [],
              ),
              Course(
                name: 'Lịch sử Đảng Cộng sản Việt Nam',
                credits: 2,
                id: 'BAA00104',
                type: CourseType.required,
                status: CourseStatus.inProgress,
                prerequisiteCourses: [],
              ),
              Course(
                name: 'Tư tưởng Hồ Chí Minh',
                credits: 2,
                id: 'BAA00003',
                type: CourseType.required,
                status: CourseStatus.notStarted,
                prerequisiteCourses: [],
              ),
            ],
          ),
          CourseGroup(
            id: '1.2',
            name: 'Khoa học xã hội - Kinh tế - Kỹ năng',
            description: 'Các môn học về khoa học xã hội và kinh tế',
            requiredCredits: 3,
            optionalCredits: 2,
            courses: [
              Course(
                name: 'Pháp luật đại cương',
                credits: 3,
                id: 'BAA00004',
                type: CourseType.required,
                status: CourseStatus.inProgress,
                prerequisiteCourses: [],
              ),
              Course(
                name: 'Kinh tế đại cương',
                credits: 2,
                id: 'BAA00005',
                type: CourseType.optional,
                status: CourseStatus.completed,
                score: 6.7,
                prerequisiteCourses: [],
              ),
              Course(
                name: 'Tâm lý đại cương',
                credits: 2,
                id: 'BAA00006',
                type: CourseType.optional,
                status: CourseStatus.notStarted,
                prerequisiteCourses: [],
              ),
              Course(
                name: 'Phương pháp luận sáng tạo',
                credits: 2,
                id: 'BAA00007',
                type: CourseType.optional,
                status: CourseStatus.notStarted,
                prerequisiteCourses: [],
              ),
            ],
          ),
          CourseGroup(
            id: '1.3',
            name: 'Toán - Khoa học tự nhiên',
            description: 'Các môn học về toán và khoa học tự nhiên',
            requiredCredits: 20,
            optionalCredits: 0,
            courses: [
              Course(
                name: 'Vi tích phân 1B',
                credits: 3,
                id: 'MTH00003',
                type: CourseType.required,
                status: CourseStatus.completed,
                score: 6.5,
                prerequisiteCourses: [],
              ),
              Course(
                name: 'Thực hành Vi tích phân 1B',
                credits: 1,
                id: 'MTH00081',
                type: CourseType.required,
                status: CourseStatus.completed,
                score: 6.5,
                prerequisiteCourses: [],
              ),
              Course(
                name: 'Vi tích phân 2B',
                credits: 3,
                id: 'MTH00004',
                type: CourseType.required,
                status: CourseStatus.inProgress,
                prerequisiteCourses: [],
              ),
              Course(
                name: 'Thực hành Vi tích phân 2B',
                credits: 1,
                id: 'MTH00082',
                type: CourseType.required,
                status: CourseStatus.inProgress,
                prerequisiteCourses: [],
              ),
              Course(
                name: 'Đại số tuyến tính',
                credits: 3,
                id: 'MTH00030',
                type: CourseType.required,
                status: CourseStatus.inProgress,
                prerequisiteCourses: [],
              ),
              Course(
                name: 'Thực hành Đại số tuyến tính',
                credits: 1,
                id: 'MTH00083',
                type: CourseType.required,
                status: CourseStatus.inProgress,
                prerequisiteCourses: [],
              ),
              Course(
                name: 'Xác suất thống kê',
                credits: 3,
                id: 'MTH00040',
                type: CourseType.required,
                status: CourseStatus.completed,
                score: 8.0,
                prerequisiteCourses: [],
              ),
              Course(
                name: 'Thực hành Xác suất thống kê',
                credits: 1,
                id: 'MTH00085',
                type: CourseType.required,
                status: CourseStatus.completed,
                score: 8.0,
                prerequisiteCourses: [],
              ),
              Course(
                name: 'Toán rời rạc',
                credits: 3,
                id: 'MTH00041',
                type: CourseType.required,
                status: CourseStatus.completed,
                score: 10,
                prerequisiteCourses: [],
              ),
              Course(
                name: 'Thực hành Toán rời rạc',
                credits: 1,
                id: 'MTH00086',
                type: CourseType.required,
                status: CourseStatus.completed,
                score: 10,
                prerequisiteCourses: [],
              ),
            ],
          ),
          CourseGroup(
            id: '1.4',
            name: 'Toán tự chọn',
            description: 'Các môn học toán tự chọn',
            requiredCredits: 0,
            optionalCredits: 4,
            courses: [
              Course(
                name: 'Toán học tổ hợp',
                credits: 4,
                id: 'MTH00050',
                type: CourseType.optional,
                status: CourseStatus.inProgress,
                prerequisiteCourses: [],
              ),
              Course(
                name: 'Lý thuyết đồ thị',
                credits: 4,
                id: 'CSC00008',
                type: CourseType.optional,
                status: CourseStatus.notStarted,
                prerequisiteCourses: [],
              ),
            ],
          ),
          CourseGroup(
            id: '1.5',
            name: 'Toán tự chọn nâng cao',
            description: 'Các môn học toán tự chọn nâng cao',
            requiredCredits: 0,
            optionalCredits: 4,
            courses: [
              Course(
                name: 'Toán ứng dụng và thống kê',
                credits: 4,
                id: 'MTH00051',
                type: CourseType.optional,
                status: CourseStatus.notStarted,
                prerequisiteCourses: [],
              ),
              Course(
                name: 'Phương pháp tính',
                credits: 4,
                id: 'MTH00052',
                type: CourseType.optional,
                status: CourseStatus.inProgress,
                prerequisiteCourses: [],
              ),
              Course(
                name: 'Lý thuyết số',
                credits: 4,
                id: 'MTH00053',
                type: CourseType.optional,
                status: CourseStatus.notStarted,
                prerequisiteCourses: [],
              ),
              Course(
                name: 'Phép tính vị từ',
                credits: 4,
                id: 'MTH00054',
                type: CourseType.optional,
                status: CourseStatus.notStarted,
                prerequisiteCourses: [],
              ),
            ],
          ),
          CourseGroup(
            id: '1.6',
            name: 'Khoa học tự nhiên tự chọn',
            description: 'Các môn học khoa học tự nhiên tự chọn',
            requiredCredits: 0,
            optionalCredits: 6,
            courses: [
              Course(
                name: 'Hoá đại cương 1',
                credits: 3,
                id: 'CHE00001',
                type: CourseType.optional,
                status: CourseStatus.notStarted,
                prerequisiteCourses: [],
              ),
              Course(
                name: 'Hoá đại cương 2',
                credits: 3,
                id: 'CHE00002',
                type: CourseType.optional,
                status: CourseStatus.notStarted,
                prerequisiteCourses: [],
              ),
              Course(
                name: 'Thực hành Hoá đại cương 1',
                credits: 2,
                id: 'CHE00081',
                type: CourseType.optional,
                status: CourseStatus.notStarted,
                prerequisiteCourses: [],
              ),
              Course(
                name: 'Thực hành Hoá đại cương 2',
                credits: 2,
                id: 'CHE00082',
                type: CourseType.optional,
                status: CourseStatus.notStarted,
                prerequisiteCourses: [],
              ),
              Course(
                name: 'Sinh đại cương 1',
                credits: 3,
                id: 'BIO00001',
                type: CourseType.optional,
                status: CourseStatus.notStarted,
                prerequisiteCourses: [],
              ),
              Course(
                name: 'Sinh đại cương 2',
                credits: 3,
                id: 'BIO00002',
                type: CourseType.optional,
                status: CourseStatus.notStarted,
                prerequisiteCourses: [],
              ),
              Course(
                name: 'Thực hành Sinh đại cương 1',
                credits: 1,
                id: 'BIO00081',
                type: CourseType.optional,
                status: CourseStatus.notStarted,
                prerequisiteCourses: [],
              ),
              Course(
                name: 'Thực hành Sinh đại cương 2',
                credits: 1,
                id: 'BIO00082',
                type: CourseType.optional,
                status: CourseStatus.notStarted,
                prerequisiteCourses: [],
              ),
              Course(
                name: 'Vật lý đại cương 1 (Cơ - nhiệt)',
                credits: 3,
                id: 'PHY00001',
                type: CourseType.optional,
                status: CourseStatus.completed,
                score: 9.5,
                prerequisiteCourses: [],
              ),
              Course(
                name: 'Vật lý đại cương 2 (Điện tử - Quang)',
                credits: 3,
                id: 'PHY00002',
                type: CourseType.optional,
                status: CourseStatus.notStarted,
                prerequisiteCourses: [],
              ),
              Course(
                name: 'Thực hành Vật lý đại cương',
                credits: 2,
                id: 'PHY00081',
                type: CourseType.optional,
                status: CourseStatus.notStarted,
                prerequisiteCourses: [],
              ),
            ],
          ),
          CourseGroup(
            id: '1.7',
            name: 'Môi trường tự chọn',
            description: 'Các môn học về môi trường tự chọn',
            requiredCredits: 0,
            optionalCredits: 2,
            courses: [
              Course(
                name: 'Khoa học trái đất',
                credits: 2,
                id: 'GEO00002',
                type: CourseType.optional,
                status: CourseStatus.notStarted,
                prerequisiteCourses: [],
              ),
              Course(
                name: 'Môi trường đại cương',
                credits: 2,
                id: 'ENV00001',
                type: CourseType.optional,
                status: CourseStatus.notStarted,
                prerequisiteCourses: [],
              ),
              Course(
                name: 'Con người và môi trường',
                credits: 2,
                id: 'ENV00003',
                type: CourseType.optional,
                status: CourseStatus.notStarted,
                prerequisiteCourses: [],
              ),
            ],
          ),
          CourseGroup(
            id: '1.8',
            name: 'Tin học tự chọn',
            description: 'Các môn học tin học tự chọn',
            requiredCredits: 0,
            optionalCredits: 4,
            courses: [
              Course(
                name: 'Tin học cơ sở',
                credits: 4,
                id: 'CSC00006',
                type: CourseType.optional,
                status: CourseStatus.completed,
                score: 7.5,
                prerequisiteCourses: [],
              ),
              Course(
                name: 'Nhập môn công nghệ thông tin',
                credits: 4,
                id: 'CSC00004',
                type: CourseType.optional,
                status: CourseStatus.notStarted,
                prerequisiteCourses: [],
              ),
            ],
          ),
        ],
      ),
      Section(
        name: 'Kiến thức cơ sở ngành',
        requiredCredits: 38,
        optionalCredits: 0,
        description: 'Nền tảng cho chuyên ngành',
        id: '2',
        courseGroups: [
          CourseGroup(
            id: '2.1',
            name: 'Kiến thức cơ sở ngành',
            description: 'Các môn học cơ sở ngành bắt buộc',
            requiredCredits: 38,
            optionalCredits: 0,
            courses: [
              Course(
                name: 'Nhập môn lập trình',
                credits: 4,
                id: 'CSC10001',
                type: CourseType.required,
                status: CourseStatus.completed,
                score: 8.5,
                prerequisiteCourses: [],
              ),
              Course(
                name: 'Kỹ thuật lập trình',
                credits: 4,
                id: 'CSC10002',
                type: CourseType.required,
                status: CourseStatus.notStarted,
                prerequisiteCourses: [],
              ),
              Course(
                name: 'Phương pháp lập trình hướng đối tượng',
                credits: 4,
                id: 'CSC10003',
                type: CourseType.required,
                status: CourseStatus.inProgress,
                prerequisiteCourses: [],
              ),
              Course(
                name: 'Cấu trúc dữ liệu và giải thuật',
                credits: 4,
                id: 'CSC10004',
                type: CourseType.required,
                status: CourseStatus.notStarted,
                prerequisiteCourses: [],
              ),
              Course(
                name: 'Cơ sở dữ liệu',
                credits: 4,
                id: 'CSC10006',
                type: CourseType.required,
                status: CourseStatus.notStarted,
                prerequisiteCourses: [],
              ),
              Course(
                name: 'Hệ điều hành',
                credits: 4,
                id: 'CSC10007',
                type: CourseType.required,
                status: CourseStatus.notStarted,
                prerequisiteCourses: [],
              ),
              Course(
                name: 'Mạng máy tính',
                credits: 4,
                id: 'CSC10008',
                type: CourseType.required,
                status: CourseStatus.notStarted,
                prerequisiteCourses: [],
              ),
              Course(
                name: 'Hệ thống máy tính',
                credits: 2,
                id: 'CSC10009',
                type: CourseType.required,
                status: CourseStatus.notStarted,
                prerequisiteCourses: [],
              ),
              Course(
                name: 'Nhập môn công nghệ phần mềm',
                credits: 4,
                id: 'CSC13002',
                type: CourseType.required,
                status: CourseStatus.notStarted,
                prerequisiteCourses: [],
              ),
              Course(
                name: 'Cơ sở trí tuệ nhân tạo',
                credits: 4,
                id: 'CSC14003',
                type: CourseType.required,
                status: CourseStatus.completed,
                score: 6.5,
                prerequisiteCourses: [],
              ),
            ],
          ),
        ],
      ),
      Section(
        name: 'Kiến thức chuyên ngành',
        requiredCredits: 0,
        optionalCredits: 34,
        description: 'Kiến thức chuyên sâu về ngành học',
        id: '3',
        courseGroups: [
          CourseGroup(
            id: '3.1',
            name: 'Kiến thức chuyên ngành',
            description: 'Các môn học chuyên ngành tự chọn',
            requiredCredits: 0,
            optionalCredits: 34,
            courses: [
              Course(
                name: 'Hệ thống viễn thông',
                credits: 4,
                id: 'CSC11002',
                type: CourseType.optional,
                status: CourseStatus.notStarted,
                prerequisiteCourses: [],
              ),
              Course(
                name: 'Ứng dụng dịch vụ điện toán đám mây cho doanh nghiệp',
                credits: 4,
                id: 'CSC11114',
                type: CourseType.optional,
                status: CourseStatus.notStarted,
                prerequisiteCourses: [],
              ),
              Course(
                name: 'An toàn và bảo mật dữ liệu trong hệ thống thông tin',
                credits: 4,
                id: 'CSC12001',
                type: CourseType.optional,
                status: CourseStatus.notStarted,
                prerequisiteCourses: [],
              ),
              Course(
                name: 'Cơ sở dữ liệu nâng cao',
                credits: 4,
                id: 'CSC12002',
                type: CourseType.optional,
                status: CourseStatus.notStarted,
                prerequisiteCourses: [],
              ),
              Course(
                name: 'Hệ quản trị cơ sở dữ liệu',
                credits: 4,
                id: 'CSC12003',
                type: CourseType.optional,
                status: CourseStatus.notStarted,
                prerequisiteCourses: [],
              ),
              Course(
                name: 'Phân tích thiết kế hệ thống thông tin',
                credits: 4,
                id: 'CSC12004',
                type: CourseType.optional,
                status: CourseStatus.notStarted,
                prerequisiteCourses: [],
              ),
              Course(
                name: 'Thương mại điện tử',
                credits: 4,
                id: 'CSC12005',
                type: CourseType.optional,
                status: CourseStatus.notStarted,
                prerequisiteCourses: [],
              ),
              Course(
                name: 'Môi trường và công cụ tiếp thị số',
                credits: 4,
                id: 'CSC12112',
                type: CourseType.optional,
                status: CourseStatus.notStarted,
                prerequisiteCourses: [],
              ),
              Course(
                name: 'Nhập môn quản trị mối quan hệ khách hàng - sản phẩm',
                credits: 4,
                id: 'CSC12113',
                type: CourseType.optional,
                status: CourseStatus.notStarted,
                prerequisiteCourses: [],
              ),
              Course(
                name: 'Kiểm thử phần mềm',
                credits: 4,
                id: 'CSC13003',
                type: CourseType.optional,
                status: CourseStatus.notStarted,
                prerequisiteCourses: [],
              ),
              Course(
                name: 'Quản lý dự án phần mềm',
                credits: 4,
                id: 'CSC13006',
                type: CourseType.optional,
                status: CourseStatus.notStarted,
                prerequisiteCourses: [],
              ),
              Course(
                name: 'Phát triển ứng dụng web',
                credits: 4,
                id: 'CSC13008',
                type: CourseType.optional,
                status: CourseStatus.notStarted,
                prerequisiteCourses: [],
              ),
              Course(
                name: 'Phát triển phần mềm cho thiết bị di động',
                credits: 4,
                id: 'CSC13009',
                type: CourseType.optional,
                status: CourseStatus.notStarted,
                prerequisiteCourses: [],
              ),
              Course(
                name: 'Thiết kế phần mềm',
                credits: 4,
                id: 'CSC13010',
                type: CourseType.optional,
                status: CourseStatus.notStarted,
                prerequisiteCourses: [],
              ),
              Course(
                name: 'Lập trình web 1',
                credits: 4,
                id: 'CSC13119',
                type: CourseType.optional,
                status: CourseStatus.notStarted,
                prerequisiteCourses: [],
              ),
              Course(
                name: 'Lập trình web 2',
                credits: 4,
                id: 'CSC13120',
                type: CourseType.optional,
                status: CourseStatus.notStarted,
                prerequisiteCourses: [],
              ),
              Course(
                name: 'Lập trình quản lý ứng dụng 1',
                credits: 4,
                id: 'CSC13121',
                type: CourseType.optional,
                status: CourseStatus.notStarted,
                prerequisiteCourses: [],
              ),
              Course(
                name: 'Lập trình quản lý ứng dụng 2',
                credits: 4,
                id: 'CSC13122',
                type: CourseType.optional,
                status: CourseStatus.notStarted,
                prerequisiteCourses: [],
              ),
              Course(
                name: 'Học thống kê',
                credits: 4,
                id: 'CSC15004',
                type: CourseType.optional,
                status: CourseStatus.notStarted,
                prerequisiteCourses: [],
              ),
              Course(
                name: 'Thống kê máy tính và ứng dụng',
                credits: 4,
                id: 'CSC15007',
                type: CourseType.optional,
                status: CourseStatus.notStarted,
                prerequisiteCourses: [],
              ),
            ],
          ),
        ],
      ),
      Section(
        name: 'Kiến thức tốt nghiệp',
        requiredCredits: 0,
        optionalCredits: 10,
        description: 'Kiến thức tổng hợp tốt nghiệp',
        id: '4',
        courseGroups: [
          CourseGroup(
            id: '4.1',
            name: 'Kiến thức tốt nghiệp',
            description: 'Các môn học tốt nghiệp tự chọn',
            requiredCredits: 0,
            optionalCredits: 10,
            courses: [
              Course(
                name: 'Chuyên đề Tổ chức dữ liệu',
                credits: 6,
                id: 'CSC10202',
                type: CourseType.optional,
                status: CourseStatus.notStarted,
                prerequisiteCourses: [],
              ),
              Course(
                name: 'Chuyên đề thiết kế phần mềm nâng cao',
                credits: 6,
                id: 'CSC10203',
                type: CourseType.optional,
                status: CourseStatus.notStarted,
                prerequisiteCourses: [],
              ),
              Course(
                name: 'Hệ thống thông tin phục vụ trí tuệ kinh doanh',
                credits: 4,
                id: 'CSC12107',
                type: CourseType.optional,
                status: CourseStatus.notStarted,
                prerequisiteCourses: [],
              ),
              Course(
                name: 'Công nghệ mới trong phát triển phần mềm',
                credits: 4,
                id: 'CSC13115',
                type: CourseType.optional,
                status: CourseStatus.notStarted,
                prerequisiteCourses: [],
              ),
              Course(
                name: 'Phát triển ứng dụng cho thiết bị di động nâng cao',
                credits: 4,
                id: 'CSC13118',
                type: CourseType.optional,
                status: CourseStatus.notStarted,
                prerequisiteCourses: [],
              ),
              Course(
                name: 'Đồ án Phần mềm',
                credits: 6,
                id: 'CSC13123',
                type: CourseType.optional,
                status: CourseStatus.notStarted,
                prerequisiteCourses: [],
              ),
            ],
          ),
        ],
      ),
    ];
    return sections;
  }

}
